// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scacnshkxfrahxarjrwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjYWNuc2hreGZyYWh4YXJqcndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDgzNjQsImV4cCI6MjA2OTMyNDM2NH0.8C2hjvcfwy1fXzptRLOTGJJEYNg5ImRaHzgOiUJgVOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});